-- +goose Up
CREATE TABLE profiles (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL
);
THIS IS INTENTIONALLY INVALID SQL STATEMENT;

-- +goose Down
DROP TABLE IF EXISTS profiles;
